# Generated by Django 2.0 on 2018-02-14 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0005_remove_opcio_vots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vot',
            name='consulta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vota.Consulta'),
        ),
        migrations.AlterField(
            model_name='vot',
            name='usuari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
