# Generated by Django 2.0 on 2018-01-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcio',
            name='vots',
            field=models.IntegerField(default=0),
        ),
    ]
